package com.github.henryouly.leanback;

/**
 * TODO: Insert description here. (generated by henryou)
 */
public final class Constants {
  public static final String ACTION_ON_MESSAGE = "com.github.henryouly.leanback.ON_MESSAGE";

  public static final String SENDER_ID = "527020451304";
  
  public static final String FIELD_MESSAGE = "msg";
}
